#!/usr/bin/env bash

dont_export=$(/usr/libexec/PlistBuddy -c 'print variablesdontexport' workflow/info.plist | grep '    ' | sed -E 's/ {4}//')

echo "${dont_export}" | while IFS= read -r v; do
    if [[ $(/usr/libexec/PlistBuddy -c "print variables:$v" workflow/info.plist) ]]; then
        echo "You can't commit $v in the workflow/info.plist (Workflow config)."
        exit 1
    fi
done
