name: Build and Test
on:
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!.gitignore'
      - '!LICENSE'
      - '!*.md'

jobs:
  ci:
    uses: rwilgaard/.github/.github/workflows/go-alfred-build.yaml@v1
