name: Build and Test

on:
  push:
    branches: ['**']
    paths:
      - '**'
      - '!.gitignore'
      - '!LICENSE'
      - '!*.md'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ~1.23

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.2

      - name: Run vet.
        run: make vet

      - name: Run lint.
        run: make lint

  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: [lint]
    strategy:
      matrix:
        os: [macos-14, macos-15, ubuntu-24.04]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ~1.23

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Create universal binary
        if: ${{ matrix.os != 'ubuntu-24.04' }}
        run: |
          make universal-binary
